version: '3.1'
services:
  db:
    image: mysql:8
    container_name: $CODENAME-mysql
    restart: unless-stopped
    user: "${UID}:${GID}"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - $MYSQL_PORT:3306
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/mysql.log:/var/log/mysql/mysql.log
  app:
    build: .
    image: $CODENAME-app
    container_name: $CODENAME-app
    restart: unless-stopped
    user: ${UID}:${UID}
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d/:/usr/local/etc/php/local.conf.d/"
    ports:
      - 9000:9000
    depends_on:
      - db
    volumes:
      - ./app:/app
      - ./php.ini:/usr/local/etc/php/local.conf.d/local.ini
